// dummy-data.ts
import { Transaction } from "./model/transaction";

export const transactions: Transaction[] = [
  {
    id: "t1",
    type: "income",
    amount: 3500,
    date: "2025-01-01",
    wallet: "Bank Account",
    description: "January Salary",
    category: null,
    receiptImage: null,
  },
  {
    id: "t2",
    type: "expense",
    amount: 120,
    date: "2025-01-03",
    category: "Food",
    description: "Lunch at cafe",
    receiptImage: "https://example.com/receipt1.jpg",
    wallet: null,
  },
  {
    id: "t3",
    type: "expense",
    amount: 80,
    date: "2025-01-05",
    category: "Transport",
    description: "Taxi fare",
    wallet: null,
    receiptImage: null,
  },
  {
    id: "t4",
    type: "income",
    amount: 500,
    date: "2025-01-10",
    wallet: "Cash",
    description: "Freelance work",
    category: null,
    receiptImage: null,
  },
  {
    id: "t5",
    type: "expense",
    amount: 950,
    date: "2025-01-12",
    category: "Shopping",
    description: "Clothes & accessories",
    wallet: null,
    receiptImage: null,
  },
  {
    id: "t6",
    type: "income",
    amount: 200,
    date: "2025-01-15",
    wallet: "Savings Account",
    description: "Interest earned",
    category: null,
    receiptImage: null,
  },
];
